# Generated by Django 3.1.7 on 2021-02-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
